--- 
data_items: []

tags: 
- transport
- distance
- passenger
- plane
- transport
- freight
- flight
- air
- aeroplane
- airplane
provenance: 
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: Plane
