--- 
data_items: []

tags: 
- deprecated
- transport
- road
- large_goods_vehicle
- lorry
- truck
- GHGP
- biofuel
- global
- calculation
- emission_factor
- biogenic
- GHGP_cross_sector
- GHGP_adipic_acid_sector
- GHGP_aluminum_sector
- GHGP_ammonia_sector
- GHGP_cement_sector
- GHGP_hcfc22_sector
- GHGP_iron_and_steel_sector
- GHGP_lime_sector
- GHGP_nitric_sector
- GHGP_pulp_and_paper_sector
- GHGP_refrigeration_sector
- GHGP_semiconductor_sector
- GHGP_wood_sector
provenance: http://www.ghgprotocol.org/calculation-tools/all-tools
gallery: 
show: "1"
authority: enterprise
ivds: 
  source: 
  fuelType: Type of biofuel used
  distance: Distance travelled
  kgCO2PerMile: "Distance-based (biomass) CO2 emissions factor "
wikiname: Other_regional_light_goods_biofuel_truck
