--- 
data_items: []

provenance: http://www.energystar.gov/index.cfm?c=home.index
tags: 
- energy_star
- appliances
- US
- entertainment
authority: enterprise
show: "1"
gallery: 
ivds: {}

wikiname: Energy_Star_Entertainment
