--- 
data_items: []

tags: 
- fluorinated_compound
- FC
- calculation
- mass_balance
- direct
- global
- IPCC
- IPCC_tier1
- IPCC_industry_chemical
- IPCC_industry
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/3_Volume3/V3_3_Ch3_Chemical_Industry.pdf|IPCC-NGGIP]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  compound: "Name of specific fluorinated compound "
  mass: Quantity of fluorinated compound produced
  type: Type of fluorinated compound
  massPerMass: Quantity of emissions per quantity of production
  source: 
  returnCO2e: 
wikiname: Generic_fluorinated_compound_production
usages:
  default : { returnCO2e : forbidden, compound : optional, massPerMass : optional }
  
