--- 
data_items: []

tags: 
- deprecated
- transport
- car
- passenger
- GHGP
provenance: http://www.ghgprotocol.org/
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: Generic_car_transport_GHGP
