--- 
data_items: []

tags: 
- carbonate
- limestone
- dolomite
- EPA
- IPCC
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/3_Volume3/V3_2_Ch2_Mineral_Industry.pdf|IPCC-NGGIP]]"
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: Miscellaneous_carbonate_consumption
