--- 
data_items: []

tags: 
- prebake
- GHGP
- GHGP_aluminum_sector
- aluminium
- IPCC
- IPCC_tier2
- IPCC_tier3
- IPCC_industry
- IPCC_industry_metal
- EPA
- EPA_mandatory
- EPA_mandatory_aluminum
- climate_leaders
- calculation
- direct
- mass_balance
- global
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/index.html|IPCC]] - [[http://www.ghgprotocol.org/calculation-tools/all-tools|Greenhouse Gas Protocol]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  sulphurQuantity: Sulphur content (wt. %) in baked anodes
  ashQuantity: Ash content (wt. %) in baked anodes
  anodeQuantity: Quantity of baked anode used per unit of aluminium produced
  type: No choice of scenarios is necessary in this methodology. All information is provided as activity data
  aluminiumQuantity: Quantity of primary aluminium produced
  source: 
wikiname: Aluminium_prebake_electrolysis
name: "IPCC methodology for aluminium production CO2 emissions - prebake electrolysis"
usages:
  default: { sulphurQuantity : optional, ashQuantity : optional }

