--- 
data_items: []

tags: 
- paper
- pulp
- ICFPA
- EPA
- EPA_mandatory
- EPA_mandatory_pulp_and_paper
- wood
- biomass
- GHGP
- GHGP_pulp_and_paper_sector
- calculation
- direct
- mass_balance
- global
provenance: "[[http://www.wbcsd.org/web/projects/forestry/Pulp-and-Paper-Tool-Guidance.pdf|ICFPA]]"
gallery: "nil"
show: "1"
authority: enterprise
ivds: 
  energyPerMassNet: Net calorific / lower heating value of pulping liquor
  mass: Quantity of pulping liquor consumed
  energy: Quantity of energy consumed
  carbonContent: Carbon content of liquor (percent) weight)
  type: Type of pulping liquor
  energyPerMassGross: Gross calorific / higher heating value of pulping liquor
  source: 
  useGross: Set to 'true' to indicate energy based on the gross calorific / higher heating value
  woodFurnish: Type of wood furnish
  oxidationCorrectionFactor: Fraction of original quantity which is oxidised completely
wikiname: Pulping_liquor_consumption
name: "ICFPA methodology for pulping liquor combustion"
usages:
  byMass: { energy : ignored, useGross : ignored }
  byEnergy: { mass : forbidden, useGross : optional }
  order: [ byMass, byEnergy ]
