--- 
data_items: []

tags: 
- IPCC
- ferroalloy
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/vol3.html|IPCC-NGGIP]]"
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: Ferroalloy_production
