--- 
data_items: []

tags: 
- IPCC
- EPA
- EPA_mandatory
- EPA_mandatory_lead
- lead
- IPCC_tier1
- IPCC_tier2
- IPCC_industry
- IPCC_industry_metal
- calculation
- direct
- emission_factor
- global
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/vol3.html|IPCC-NGGIP]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  leadProductionBySource: drill-down used to specify the source or furnace type used
  productQuantity: user-supplied value for the quantity of lead produced
  massCO2PerMassProduct: the emission factor for the source or furnace type selected
  source: 
wikiname: Lead_production
usages:
  default: { massCO2PerMassProduct : optional }
