--- 
data_items: []

provenance: "[[http://www.ghgprotocol.org/calculation-tools/all-tools|GHGP  Protocol]]"
tags: 
- deprecated
- transport
- car
- passenger
- GHGP
- US
- calculation
- emission_factor
- direct
- GHGP_cross_sector
- GHGP_adipic_acid_sector
- GHGP_aluminum_sector
- GHGP_ammonia_sector
- GHGP_cement_sector
- GHGP_hcfc22_sector
- GHGP_iron_and_steel_sector
- GHGP_lime_sector
- GHGP_nitric_sector
- GHGP_pulp_and_paper_sector
- GHGP_refrigeration_sector
- GHGP_semiconductor_sector
- GHGP_wood_sector
authority: enterprise
show: "1"
gallery: 
ivds: 
  gCH4PerMile: Distance-based CH4 emissions factor
  occupancy: 
  yearOfManufacture: Year of vehicle manufacture
  gN2OPerMile: Distance-based N2O emissions factor
  fuelType: Vehicle fuel type
  source: 
  kgCO2PerMile: Distance-based CO2 emissions factor
  distance: Distance travelled
wikiname: US_car_transport
usages:
  default: { occupancy : optional }
