--- 
data_items: []

tags: deprecated
provenance: ECCM
gallery: 
show: "1"
authority: tentative
ivds: 
  kgCO2PerPound: 
  type: 
  currencyGBP: 
  source: 
  currencyGBPPerMonth: 
wikiname: Personal
usages:
  default: { currencyGBP : compulsory, currencyGBPPerMonth : ignored }

