--- 
data_items: []

tags: 
- iron
- steel
- GHGP
- IPCC
- EPA
provenance: "  Based on the GHG Protocol [[http://www.ghgprotocol.org/calculation-tools/all-tools|worksheet]] for Iron and Steel"
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: Production_Iron_and_Steel
