--- 
data_items: []

tags: 
- aluminium
- industry
- GHGP
- IPCC
- IAI
- EPA
provenance: Based on the WRI Greenhouse Gas Protocol Aluminium [[http://www.ghgprotocol.org/calculation-tools/all-tools|worksheets]]
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: Aluminium
