--- 
data_items:
- doc: Average
  drills:
  - - type
    - rigid
  - - size
    - 3.5-7.5t
  - - percentageLaden
    - 40
- doc: Average
  drills:
  - - type
    - rigid
  - - size
    - 7.5-17t
  - - percentageLaden
    - 37
- doc: Average
  drills:
  - - type
    - rigid
  - - size
    - greater than 17t
  - - percentageLaden
    - 55
- doc: Average
  drills:
  - - type
    - articulated
  - - size
    - 3.5-33t
  - - percentageLaden
    - 43
- doc: Average
  drills:
  - - type
    - articulated
  - - size
    - greater than 33t
  - - percentageLaden
    - 60
tags: 
- deprecated
- defra
- heavy_goods
- trucks
- UK
- calculation
- emission_factor
- direct
provenance: http://www.defra.gov.uk/environment/business/reporting/conversion-factors.htm
gallery: 
show: "1"
authority: enterprise
ivds: 
  kgCO2PerVehicleKm: CO2 emission factor
  size: size class of vehicle
  kgCO2ePerKmForN2O: N2O emission factor
  type: 
  source: 
  distance: 
  kgCO2ePerKmForCH4: CH4 emission factor
  percentageLaden: percentage of vehicle filled with freight
wikiname: Heavy_Goods_Defra
