--- 
data_items: []

tags: 
- deprecated
- transport
- car
- passenger
- GHGP
- global
- calculation
- emission_factor
- direct
- GHGP_cross_sector
- GHGP_adipic_acid_sector
- GHGP_aluminum_sector
- GHGP_ammonia_sector
- GHGP_cement_sector
- GHGP_hcfc22_sector
- GHGP_iron_and_steel_sector
- GHGP_lime_sector
- GHGP_nitric_sector
- GHGP_pulp_and_paper_sector
- GHGP_refrigeration_sector
- GHGP_semiconductor_sector
- GHGP_wood_sector
provenance: "[[http://www.ghgprotocol.org/calculation-tools/all-tools|GHG Protocol]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  occupancy: 
  source: 
  fuelType: Vehicle fuel type
  distance: Distance travelled
  kgCO2PerMile: Distance-based CO2 emissions factor
wikiname: Other_regional_car_transport
usages:
  default: { occupancy : optional }
