--- 
data_items: []

tags: 
- deprecated
- electricity
- GHGP
- country
- calculation
- direct
- emission_factor
- global
- GHGP_cross_sector
- GHGP_adipic_acid_sector
- GHGP_aluminum_sector
- GHGP_ammonia_sector
- GHGP_cement_sector
- GHGP_hcfc22_sector
- GHGP_iron_and_steel_sector
- GHGP_lime_sector
- GHGP_nitric_sector
- GHGP_pulp_and_paper_sector
- GHGP_refrigeration_sector
- GHGP_semiconductor_sector
- GHGP_wood_sector
provenance: Based on the WRI GHG Protocol [[http://www.ghgprotocol.org/calculation-tools/all-tools|worksheet]] for purchased electricity
gallery: 
show: "1"
authority: enterprise
ivds: 
  energyPerTime: Rate of energy consumption
  country: Country or international region
  massCH4PerEnergy: Electricity CH4 emission factor for specified //**country**//
  totalArea: Total area of facility
  massN2OPerEnergy: Electricity N2O emission factor for specified //**country**//
  responsibleArea: Area of facility being accounted for
  source: 
  massCO2PerEnergy: Electricity CO2 emission factor for specified //**country**//
wikiname: Electricity_by_Country
usages:
  totalEmissions : { totalArea : forbidden, responsibleArea : forbidden }
  byResponsibleArea : { totalArea : compulsory, responsibleArea : compulsory }
  order : [ totalEmissions, byResponsibleArea ] 
