--- 
data_items: []

tags: 
- transport
- transport
- plane
- aircraft
- fuel
- corinair
provenance: http://www.eea.europa.eu/publications/EMEPCORINAIR5/page017.html
gallery: 
show: "0"
authority: 
ivds: {}

wikiname: Specific_plane_transport
