--- 
data_items: []

provenance: http://www.ghgprotocol.org/calculation-tools/all-tools
tags: 
- GHGP
- india
- electricity
authority: enterprise
show: "0"
gallery: 
ivds: {}

wikiname: Electricity_India
