--- 
data_items: []

tags: 
- transport
- GHGP
provenance: "[[http://www.ghgprotocol.org/calculation-tools/all-tools|Greenhouse Gas Protocol]]"
gallery: 
show: "0"
authority: enterprise
ivds: 
  
wikiname: Road_transport_by_Greenhouse_Gas_Protocol
usages:
  
