--- 
provenance: "[[http://projects.bre.co.uk/sap2005/|BRE SAP]]"
tags: 
- domestic
- housing
- dwelling
- heating
- energy
- lighting
- standard
- methodology
authority: 
show: "1"
wikiname: Standard_Assessment_Procedure
