--- 
data_items: []

tags: 
- oil
- gas
- coal
- industry
- fugitive
- CH4
- N2O
- IPCC
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/2_Volume2/V2_4_Ch4_Fugitive_Emissions.pdf|IPCC]]"
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: Fugitive_emissions_from_mining
