--- 
data_items: []

tags: 
- deprecated
- transport
- van
- light_goods
- IPCC
- distance
- fuel
- US
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/2_Volume2/V2_3_Ch3_Mobile_Combustion.pdf|IPCC]]"
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: US_light_goods_transport_IPCC
