--- 
data_items: []

provenance: "[[http://www.clm.nl/index_eng.php?|CLM]]"
tags: 
- CLM
- lca
- food
- packaging
- agriculture
- standard
- methodology
authority: Enterprise
show: "0"
gallery: 
ivds: 
wikiname: Centre_for_Agriculture_and_Environment
