--- 
data_items: []

tags: 
- energy_season
- calculation
- UK
provenance: EST DEFRA AMEE
gallery: 
show: "1"
authority: Recommended
ivds: 
  usagePerQuarter: 
  name: 
  energy: 
  percentage: 
  source: 
wikiname: UK_Seasonal_Alternative
