--- 
data_items: []

tags: 
- transport
- car
- engine_size
- band
provenance: 
gallery: 
show: "1"
authority: enterprise
ivds: 
  kgCO2PerKmMin: Minimum value of the band
  kgCO2PerKm: Value used in a profile item calculation
  band: Car category banding
  distanceKmPerMonth: Distance travelled per month
  kgCO2PerKmMax: Maximum value of the band
  source: 
  distance: Distance travelled
wikiname: Car_transport_by_band
