--- 
data_items: []

tags: 
- fuel
- defra
- stationary
- combustion
- direct
- indirect
- life_cycle
provenance: "[[http://www.defra.gov.uk/environment/economy/business-efficiency/reporting|DEFRA]]"
gallery: 
show: "0"
authority: enterprise
ivds: 
  
wikiname: Fuel_combustion_by_DEFRA
