--- 
data_items: []

tags: 
- GHGP
- GHGP_hcfc22_sector
- HCFC_22
- IPCC
- IPCC_tier1
- IPCC_industry
- IPCC_industry_chemical
- calculation
- direct
- emission_factor
- global
provenance: "Based on the GHG Protocol [[http://www.ghgprotocol.org/calculation-tools/all-tools|worksheet]] for HCFC-22 "
gallery: 
show: "1"
authority: enterprise
ivds: 
  defEmissFact: Used if no HFC-23 emission factor is entered
  timeHFC23: Default of 1 used if none entered
  emissFact: Amount of HFC-23 produced per quantity HFCF-22
  type: Select the plant type from the drill options below
  quantityHCFC22: 
  source: 
wikiname: HCFC22_production_data_only
usages:
  default : { emissFact : optional, timeHFC23 : optional }

