--- 
provenance: "[[http://www.decc.gov.uk/en/content/cms/what_we_do/lc_uk/crc/user_guidance/user_guidance.aspx|January 2010 CRC factors]], [[http://www.decc.gov.uk/en/content/cms/consultations/crc/crc.aspx|March 2009 Draft Consultation]]"
tags: 
- CRC
- fuel
- energy
- business
- UK
- standard
- methodology
authority: 
show: "1"
wikiname: Carbon_Reduction_Commitment
