--- 
provenance: "[[http://www.ghgprotocol.org/about-ghgp|Greenhouse Gas Protocol]]"
tags: 
- GHGP
- reporting
- tools
- corporate_standard
- scope
- standard
- methodology
authority: 
show: "1"
wikiname: Greenhouse_Gas_Protocol
