--- 
provenance: "[[http://www.epa.gov/cleanenergy/energy-resources/egrid/index.html|EPA-eGRID]]"
tags: 
- egrid
- US
- GHGP
- electricity
- standard
- methodology
authority: 
gallery: nil
show: "1"
wikiname: US_E_grid
name: "Emissions and Generation Resource Integrated Database (eGRID)"
