--- 
data_items: []

tags: 
- industry
- fugitive
- CH4
- IPCC
- mining
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/2_Volume2/V2_4_Ch4_Fugitive_Emissions.pdf|IPCC]]"
gallery: 
show: "0"
authority: 
ivds: {}

wikiname: Abandoned_underground_mines
