--- 
data_items: []

tags: 
- transport
- passenger
- car
- distance
- mobile
- fuel
- US
- calculation
- emission_factor
- direct
provenance: "[[http://www.fueleconomy.gov|www.fueleconomy.gov]]"
gallery: |-
 <%= chart :dependent => 'mpgCombined', :x => 'manufacturer' %>
show: "1"
authority: enterprise
ivds: 
  mpgCombined: Combined city/highway usage fuel consumption
  mpgHighway: Highway usage fuel consumption
  mpgOwn: User determined fuel consumption
  line: Car model
  class: Car class category
  distanceMilesPerMonth: Distance travelled per month
  drivingType: Specify "own", "city", "highway", or "combined" driving type
  releaseDate: 
  driveSystem: Front/rear drive system
  engineSize: Engine size
  mpgCity: City usage fuel consumption
  transmission: Transmission type
  manufacturer: Car manufacturer
  indexNumber: 
  ownFuelConsumption: Manufacturer fuel consumption
  source: 
  fuelType: Car fuel type
  cylinders: Cylinder numbers
  distance: Distance travelled
  year: Year of the car model
wikiname: "US2_specific_car_transport"
name: "US car models"
usages:
  default: { ownFuelConsumption : optional, drivingType : optional }
