--- 
data_items: []

tags: 
- agriculture
- IPCC
- IPCC_agriculture
- IPCC_agriculture_livestock
- IPCC_tier1
- livestock
- manure
- CH4
- calculation
- direct
- emission_factor
- global
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/4_Volume4/V4_10_Ch10_Livestock.pdf|IPCC]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  livestockNumber: Total number of livestock (head count) under consideration
  geographicContext: Geographic/developmental context in which livestock kept
  livestockType: Type of livestock
  source: 
  temperature: Average annual temperature at location under consideration
  massCH4PerHeadPerTime: Annual manure-associated methane emissions per head of livestock
wikiname: Other_manure_methane_emissions
name: "IPCC methodology for manure sourced methane - other livestock"
