--- 
data_items: []

tags: 
- cement
- GHGP
- IPCC
- CSI
- EPA
provenance: Based on the GHG Protocol worksheets [[http://www.ghgprotocol.org/calculation-tools/all-tools|worksheets]] for cement production
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: Cement
