--- 
data_items: []

provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/3_Volume3/V3_2_Ch2_Mineral_Industry.pdf|IPCC-NGGIP]]"
tags: 
- cement
- IPCC
- EPA
- clinker
authority: enterprise
show: "0"
gallery: 
ivds: {}

wikiname: IPCC_cement_methodologies
