--- 
data_items: []

tags: 
- agriculture
- IPCC
- livestock
- manure
- CH4
- N2O
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/4_Volume4/V4_05_Ch5_Cropland.pdf|IPCC]]"
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: Livestock
