--- 
provenance: "[[http://people.bath.ac.uk/cj219/|Bath University]]"
tags: 
- embodied
- construction
- materials
- lca
- ice
- standard
- methodology
authority: 
show: "1"
wikiname: Embodied_Inventory_of_carbon_and_energy_ICE
name: "Inventory of Carbon and Energy (ICE)"
