--- 
provenance: Based on [[http://ostfoldforskning.no/uploads/prosjektsider/publikasjon/Electricity_Disclosure_in_the_Nordic_Countries_-_october_2011.pdf|Recommendation for Electricity Disclosure in the Nordic Countries]].
tags: 
- electricity
- nordic
- methodology
- disclosure
- residual_mix
- EU
show: "1"
authority: enterprise
wikiname: Nordic_Electricity
name: "Nordic Residual Grid Mix Disclosure"
