--- 
data_items: []

tags: 
- agriculture
- IPCC
- IPCC_agriculture
- IPCC_agriculture_soil
- IPCC_tier1
- soil
- fertilizer
- lime
- calculation
- direct
- mass_balance
- global
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/4_Volume4/V4_11_Ch11_N2O&CO2.pdf|IPCC]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  type: Carbonate mineral used in liming
  massPerMass: Carbon content of carbonate mineral
  massUsed: Quantity of lime (carbonate mineral) applied
  source: 
wikiname: Soil_liming
name: "IPCC methodology for liming of managed soils"
