---
data_items: []

tags: 
- fuel
- stationary
- combustion
- EPA
- US
- climate_leaders
provenance: "[[http://www.epa.gov/stateply/resources/index.html|US EPA/Climate Leaders]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
wikiname: EPA_stationary_combustion
