--- 
data_items: []

tags: 
- deprecated
- transport
- road
- large_goods_vehicle
- lorry
- truck
- GHGP
provenance: http://www.ghgprotocol.org/
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: Light_goods_truck_transport
