--- 
data_items: []

tags: 
- waste
- combustion
- IPCC
- IPCC_tier1
- IPCC_waste
- IPCC_waste_bio
- calculation
- mass_balance
- emission_factor
- direct
- global
- domestic
- municipal
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/5_Volume5/V5_5_Ch5_IOB.pdf|IPCC]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  isWetWeight: Set to 'true' to indicate quantity is specified on a wet-weight basis
  massCH4PerMass: Methane emissions factor
  totalCarbonContent: Total carbon (fossil + recent) in waste by proportion
  mass: Quantity of waste burned
  oxidationFactor: "Fraction of waste oxidised during combustion "
  technology: Technology used for waste combustion
  method: Method of combustion
  dryMatterContent: Dry proportion of waste
  type: Type of waste burned
  fossilFraction: "Fossil carbon in waste as a proportion of the total carbon "
  includeAllCarbon: This item is deprecated
  massN2OPerMass: Nitrous oxide emissions factor
  source: 
wikiname: Municipal_waste_combustion
usages:
  default: { includeAllCarbon : forbidden, isWetWeight : optional }
