--- 
data_items: []

tags: 
- agriculture
- IPCC
- soil
- fertilizer
- manure
- organic
provenance: http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/4_Volume4/V4_11_Ch11_N2O&CO2.pdf
gallery: 
show: "0"
authority: 
ivds: {}

wikiname: N2O_emissions_from_soil_applications
