--- 
data_items: []

tags: 
- refrigeration
- defra
provenance: "[[http://www.defra.gov.uk/environment/business/reporting/conversion-factors.htm|DEFRA]]"
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: Refrigeration
