--- 
data_items: []

tags: 
- deprecated
- transport
- bus
- GHGP
- passenger
- US
- calculation
- emission_factor
- direct
- GHGP_cross_sector
- GHGP_adipic_acid_sector
- GHGP_aluminum_sector
- GHGP_ammonia_sector
- GHGP_cement_sector
- GHGP_hcfc22_sector
- GHGP_iron_and_steel_sector
- GHGP_lime_sector
- GHGP_nitric_sector
- GHGP_pulp_and_paper_sector
- GHGP_refrigeration_sector
- GHGP_semiconductor_sector
- GHGP_wood_sector
provenance: http://www.ghgprotocol.org/calculation-tools/all-tools
gallery: 
show: "1"
authority: enterprise
ivds: 
  gN2OPerPassengerMile: Distance-based emissions factor for N2O
  numberOfPassengers: Number of passengers under consideration
  gCH4PerPassengerMile: Distance-based emissions factor for CH4
  type: Type of vehicle
  source: 
  distance: Distance travelled
  kgCO2PerPassengerMile: Distance-based emissions factor for CO2
wikiname: US_bus_transport_by_passenger
usages:
  default: { numberOfPassengers : optional }
