--- 
data_items: []

tags: 
- deprecated
- transport
- fuel
- GHGP
- biomass
- biofuel
- US
- calculation
- emission_factor
- biogenic
- GHGP_cross_sector
- GHGP_adipic_acid_sector
- GHGP_aluminum_sector
- GHGP_ammonia_sector
- GHGP_cement_sector
- GHGP_hcfc22_sector
- GHGP_iron_and_steel_sector
- GHGP_lime_sector
- GHGP_nitric_sector
- GHGP_pulp_and_paper_sector
- GHGP_refrigeration_sector
- GHGP_semiconductor_sector
- GHGP_wood_sector
provenance: http://www.ghgprotocol.org/calculation-tools/all-tools
gallery: 
show: "1"
authority: enterprise
ivds: 
  kgCO2PerUsGallon: Per fuel-quantity CO2 emissions factor
  source: 
  fuelType: Type of fuel used
  fuelQuantity: Quantity of fuel used
wikiname: US_transport_biofuel
