--- 
data_items: []

tags: 
- cooking
- electricity
- gas
- calculation
- direct
- emission_factor
- UK
provenance: "[[MTP]],[[http://www.bre.co.uk|BREDEM]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  numberOfPeople: If this is not set then the **//peopleInHousehold//** value is used in the [[Metadata|/metadata]] profile item.
  type: 
  baseKWhPerYear: 
  perPersonKWhPerYear: 
  source: 
wikiname: Hob
