--- 
provenance: "[[http://www.ecoinvent.ch/|Ecoinvent]]"
tags: 
- ecoinvent
- lca
- methodology
- elementary
- flows
- factors
- upr
- lci
- lcia
authority: 
show: "1"
wikiname: Ecoinvent_process_data
