--- 
data_items: []

tags: 
- transport
- distance
- car
- fuel
- travel
- IPCC
- US
- heavy_goods
- light_goods
- bus
- IPCC
- IPCC_tier1
- IPCC_tier2
- IPCC_tier3
- IPCC_energy
- IPCC_energy_mobile
- calculation
- emission_factor
- direct
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/2_Volume2/V2_3_Ch3_Mobile_Combustion.pdf|IPCC]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  fuelEfficiency: Fuel consumption efficiency of vehicle
  occupancy: Total vehicle occupancy
  massCH4PerDistance: Factor for methane emissions per unit distance
  fuel: Type of fuel used by vehicle
  massN2OPerDistance: Factor for nitrous oxide emissions per unit distance
  fuelConsumed: Total quantity of fuel consumed
  basis: Describes whether emissions are based on 'upper', 'lower' or 'mean' values from the range of emissions factors specified by the IPCC
  distance: Distance travelled
wikiname: US_road_transport_with_alternative_fuels_by_IPCC
usages:
  byFuelOnly: { distance : forbidden, fuelEfficiency : ignored, occupancy : optional, density : optional }
  byDistanceAndFuel: { fuelEfficiency : forbidden, occupancy : optional, density : optional }
  byDistanceAndEfficiency: { fuelConsumed : ignored, occupancy : optional, density : optional }
  order: [ byFuelOnly, byDistanceAndFuel, byDistanceAndEfficiency ]
