--- 
data_items: []

tags: 
- GHGP
- lime
- IPCC
- IAI
provenance: Based on the GHG Protocol [[http://www.ghgprotocol.org/calculation-tools/all-tools|worksheet]] for lime production
gallery: 
show: "0"
authority: enterprise
ivds: {}

wikiname: Lime
