--- 
data_items: []

tags: 
- waste
- combustion
- IPCC
- IPCC_tier1
- IPCC_waste
- IPCC_waste_bio
- calculation
- mass_balance
- direct
- global
- domestic
- municipal
- industrial
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/5_Volume5/V5_5_Ch5_IOB.pdf|IPCC]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  isWetWeight: Set to 'true' to indicate quantity is specified on a wet-weight basis
  totalCarbonContent: Total carbon (fossil + recent) in waste by proportion
  mass: Quantity of waste burned
  oxidationFactor: Proportion of waste oxidised during combustion
  fossilCarbonContent: Fossil carbon in waste by proportion
  waterContent: Water content of waste
  includeAllCarbon: This item is now deprecated
  source: 
  industry: Industrial sector
wikiname: Industrial_waste_combustion
usages:
  default: { includeAllCarbon : forbidden, isWetWeight : optional }
